### ISSUE TITLE
strange user handling

### ISSUE THREAD

**Issue by danmarsden** [vfremaux/moodle-block_shop_course_seats#4]
https://github.com/vfremaux/moodle-block_shop_course_seats/blob/master/ajax/service.php#L83

seems a bit strange to identify users based on lastname? - might be good to tidy this up or include some comments in the code to explain why you are identifying based on users lastname.

**Comment by vfremaux** [comment]
commented. Loose identity matching to accept firstname mistyping or communication errors. Keep sufficiant heuristic on lastname and email. People getting participant list names may NOT be aware those users were already there, as this user creation is a delegated function to third party users.
